# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ColorFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsColorFrame(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColorFrame()
        x.Init(buf, n + offset)
        return x

    # ColorFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorFrame
    def FrameIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ColorFrame
    def Tween(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ColorFrame
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ColorFrame
    def EasingData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .EasingData import EasingData
            obj = EasingData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ColorFrameStart(builder): builder.StartObject(4)
def ColorFrameAddFrameIndex(builder, frameIndex): builder.PrependInt32Slot(0, frameIndex, 0)
def ColorFrameAddTween(builder, tween): builder.PrependBoolSlot(1, tween, 1)
def ColorFrameAddColor(builder, color): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)
def ColorFrameAddEasingData(builder, easingData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(easingData), 0)
def ColorFrameEnd(builder): return builder.EndObject()
