# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class EasingData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEasingData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EasingData()
        x.Init(buf, n + offset)
        return x

    # EasingData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EasingData
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # EasingData
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from .Position import Position
            obj = Position()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EasingData
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def EasingDataStart(builder): builder.StartObject(2)
def EasingDataAddType(builder, type): builder.PrependInt32Slot(0, type, -1)
def EasingDataAddPoints(builder, points): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)
def EasingDataStartPointsVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def EasingDataEnd(builder): return builder.EndObject()
