# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class Options(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Options()
        x.Init(buf, n + offset)
        return x

    # Options
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Options
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OptionsStart(builder): builder.StartObject(1)
def OptionsAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def OptionsEnd(builder): return builder.EndObject()
