# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ScrollViewOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsScrollViewOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScrollViewOptions()
        x.Init(buf, n + offset)
        return x

    # ScrollViewOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScrollViewOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BackGroundImageData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def ClipEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def BgColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BgStartColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BgEndColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def ColorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScrollViewOptions
    def BgColorOpacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 255

    # ScrollViewOptions
    def ColorVector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from .ColorVector import ColorVector
            obj = ColorVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def CapInsets(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from .CapInsets import CapInsets
            obj = CapInsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def Scale9Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from .FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BackGroundScale9Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def InnerSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            from .FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScrollViewOptions
    def BounceEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def ScrollbarEnabeld(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ScrollViewOptions
    def ScrollbarAutoHide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ScrollViewOptions
    def ScrollbarAutoHideTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.2

def ScrollViewOptionsStart(builder): builder.StartObject(18)
def ScrollViewOptionsAddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def ScrollViewOptionsAddBackGroundImageData(builder, backGroundImageData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundImageData), 0)
def ScrollViewOptionsAddClipEnabled(builder, clipEnabled): builder.PrependBoolSlot(2, clipEnabled, 0)
def ScrollViewOptionsAddBgColor(builder, bgColor): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bgColor), 0)
def ScrollViewOptionsAddBgStartColor(builder, bgStartColor): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bgStartColor), 0)
def ScrollViewOptionsAddBgEndColor(builder, bgEndColor): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bgEndColor), 0)
def ScrollViewOptionsAddColorType(builder, colorType): builder.PrependInt32Slot(6, colorType, 0)
def ScrollViewOptionsAddBgColorOpacity(builder, bgColorOpacity): builder.PrependUint8Slot(7, bgColorOpacity, 255)
def ScrollViewOptionsAddColorVector(builder, colorVector): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(colorVector), 0)
def ScrollViewOptionsAddCapInsets(builder, capInsets): builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(capInsets), 0)
def ScrollViewOptionsAddScale9Size(builder, scale9Size): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(scale9Size), 0)
def ScrollViewOptionsAddBackGroundScale9Enabled(builder, backGroundScale9Enabled): builder.PrependBoolSlot(11, backGroundScale9Enabled, 0)
def ScrollViewOptionsAddInnerSize(builder, innerSize): builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(innerSize), 0)
def ScrollViewOptionsAddDirection(builder, direction): builder.PrependInt32Slot(13, direction, 0)
def ScrollViewOptionsAddBounceEnabled(builder, bounceEnabled): builder.PrependBoolSlot(14, bounceEnabled, 0)
def ScrollViewOptionsAddScrollbarEnabeld(builder, scrollbarEnabeld): builder.PrependBoolSlot(15, scrollbarEnabeld, 1)
def ScrollViewOptionsAddScrollbarAutoHide(builder, scrollbarAutoHide): builder.PrependBoolSlot(16, scrollbarAutoHide, 1)
def ScrollViewOptionsAddScrollbarAutoHideTime(builder, scrollbarAutoHideTime): builder.PrependFloat32Slot(17, scrollbarAutoHideTime, 0.2)
def ScrollViewOptionsEnd(builder): return builder.EndObject()
