# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class CapInsets(object):
    __slots__ = ['_tab']

    # CapInsets
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CapInsets
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # CapInsets
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # CapInsets
    def Width(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # CapInsets
    def Height(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateCapInsets(builder, x, y, width, height):
    builder.Prep(4, 16)
    builder.PrependFloat32(height)
    builder.PrependFloat32(width)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()
