# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ColorVector(object):
    __slots__ = ['_tab']

    # ColorVector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorVector
    def VectorX(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ColorVector
    def VectorY(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateColorVector(builder, vectorX, vectorY):
    builder.Prep(4, 8)
    builder.PrependFloat32(vectorY)
    builder.PrependFloat32(vectorX)
    return builder.Offset()
