# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class Frame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFrame(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Frame()
        x.Init(buf, n + offset)
        return x

    # Frame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Frame
    def PointFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .PointFrame import PointFrame
            obj = PointFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def ScaleFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ScaleFrame import ScaleFrame
            obj = ScaleFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def ColorFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ColorFrame import ColorFrame
            obj = ColorFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def TextureFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TextureFrame import TextureFrame
            obj = TextureFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def EventFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .EventFrame import EventFrame
            obj = EventFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def IntFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .IntFrame import IntFrame
            obj = IntFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def BoolFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .BoolFrame import BoolFrame
            obj = BoolFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def InnerActionFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .InnerActionFrame import InnerActionFrame
            obj = InnerActionFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def BlendFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .BlendFrame import BlendFrame
            obj = BlendFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FrameStart(builder): builder.StartObject(9)
def FrameAddPointFrame(builder, pointFrame): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pointFrame), 0)
def FrameAddScaleFrame(builder, scaleFrame): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(scaleFrame), 0)
def FrameAddColorFrame(builder, colorFrame): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(colorFrame), 0)
def FrameAddTextureFrame(builder, textureFrame): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(textureFrame), 0)
def FrameAddEventFrame(builder, eventFrame): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(eventFrame), 0)
def FrameAddIntFrame(builder, intFrame): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(intFrame), 0)
def FrameAddBoolFrame(builder, boolFrame): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(boolFrame), 0)
def FrameAddInnerActionFrame(builder, innerActionFrame): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(innerActionFrame), 0)
def FrameAddBlendFrame(builder, blendFrame): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(blendFrame), 0)
def FrameEnd(builder): return builder.EndObject()
