# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class ResourceData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsResourceData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResourceData()
        x.Init(buf, n + offset)
        return x

    # ResourceData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResourceData
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResourceData
    def PlistFile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResourceData
    def ResourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ResourceDataStart(builder): builder.StartObject(3)
def ResourceDataAddPath(builder, path): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)
def ResourceDataAddPlistFile(builder, plistFile): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(plistFile), 0)
def ResourceDataAddResourceType(builder, resourceType): builder.PrependInt32Slot(2, resourceType, 0)
def ResourceDataEnd(builder): return builder.EndObject()
